"""initial migrate

Revision ID: bff80ef9cc5e
Revises: e4b805b4491b
Create Date: 2024-07-02 17:01:45.435568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bff80ef9cc5e'
down_revision = 'e4b805b4491b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
